server root
{
    port			8080;
	serverName		localhost;
    root			www/;
	indexName		index.html;

	# Erreurs du Hub
    error_page  404 error_pages/404.html;
    error_page  405 error_pages/405.html;
	error_page  500 error_pages/500.html;
}

server cloud
{
    port        	8081;
	serverName		localhost;
    root        	www/;
    indexName   	cloud.html;
	uploadDir		cloud_data/;

	# Erreurs spécifiques au Cloud
    error_page  400 error_pages/400.html;
    error_page  404 error_pages/404_cloud.html;
    error_page  405 error_pages/405.html;
    error_page  500 error_pages/500.html;
}